version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run:
          name: fail on purpose
          command: exit 1

workflows:
  everymin:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test
