version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: |
          sleep 30
          echo test

workflows:
  twentyfirstmin:
    when: false
    triggers:
      - schedule:
          cron: "21 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test
