version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: |
          sleep 30
          echo test

workflows:
  everyfive:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test
